### ISSUE TITLE
Send pysedm reports on the marshal

### ISSUE THREAD

**Issue by nblago** [scizen9/sedmpy#1]
Upload the pysedm report to the marshal for each reduced spectrum.
If the quality of the classification with SNID is good (rlap > 5), then add also an autoannotation to the marshal with the classification.
We need to make sure that we mention that this is an AUTOMATIC classification and the users need to revise that carefully.

**Comment by scizen9** [comment]
The branch integrating_annots has been merged and tested on pharos.  This issue can now be closed.

**Comment by scizen9** [comment]
The branch integrating_annots has been merged and tested on pharos.  It can now be closed
