### ISSUE TITLE
project_stats has an internal server error

### ISSUE THREAD

**Issue by amdugas** [scizen9/sedmpy#10]

**Comment by amdugas** [comment]
It seems like the error probably has something to do with NaN values, but this already happened once since the server update and I fixed it by removing them all last time?

**Comment by amdugas** [comment]
It's fixed but I don't know how to restart the production website :(

**Comment by rswalters** [comment]
I restarted the production website and it does appear to be fixed.

**Comment by scizen9** [comment]
OK.  I will close this issue.
