### ISSUE TITLE
fields for spec_calib table in sedmdb

### ISSUE THREAD

**Issue by scizen9** [scizen9/sedmpy#12]
These are the fields that can be filled in by the pipeline, once they are implemented in the database:

bias_slow_master, text  - done
bias_fast_master, text - done
dome_master, text - done
hg_master, text - done
cd_master, text - done
xe_master, text - done
flat, text - done
drpver, text - done

hexagrid, text
tracematch, text
tracematch_withmasks, text
wavesolution, text
dispersionmap, text
flatmap, text
nspaxels, int
wave_rms_avg, float
wave_rms_min, float
wave_rms_max, float
width_rms_avg, float
width_rms_min, float
width_rms_max, float

**Comment by scizen9** [comment]
We also need:
utdate, text

**Comment by rswalters** [comment]
All the fields above have now been added to the spec_calib table. The function for filling out the table in db.SedmDB..SedmDB.add_spec_calib() still needs to be modified.

**Comment by scizen9** [comment]
Updated add_spec_calib() as well.

**Comment by scizen9** [comment]
need the following changes to table spec_calib:

dome -> dome_master
bias -> bias_slow_master

new column:

bias_fast_master, text

**Comment by scizen9** [comment]
sedm database updated and new columns tested.
