### ISSUE TITLE
fields for spec table in sedmdb

### ISSUE THREAD

**Issue by scizen9** [scizen9/sedmpy#13]
These are the fields that can be filled in by the pipeline, once they are implemented in the database.

cubefile, text - done
flex_x_pix, float
flex_y_pix, float
airmass, float
atmcorr, float
pos_ok, bool
srcpos, text
pos_x_spax, float
pos_y_spax, float
psf_model, text
psf_fwhm, float
psf_ell, float
psf_adr_pa, float
psf_adr_z, float
psf_adr_c2, float
fluxcal, bool
fluxcalfile, text
extr_type, text
asciifile, text - done
fitsfile, text - done
spec_calib_id - done
observation_id - done
marshal_spec_id - done

**Comment by rswalters** [comment]
All the fields above have now been added to the spec table.  The function for filling out the table in db.SedmDB..SedmDB.add_spec() still needs to be modified.

**Comment by scizen9** [comment]
Implemented and verified.
