### ISSUE TITLE
Need link on pharos website for e3d_*.fits

### ISSUE THREAD

**Issue by scizen9** [scizen9/sedmpy#24]
If users want to re-extract, they will need access to the cube data (e3d_*.fits) for each observation.
This link should be on the ifu data access page.

**Comment by rswalters** [comment]
Added in e3update branch.  Just needs to be merged into master and put on production server

**Comment by rswalters** [comment]
Just saw @amdugas put in a pull request as well.  Here is a screen shot of what the site looks like with my change.  
![example](https://user-images.githubusercontent.com/24282042/46558580-6b953d80-c8a2-11e8-8792-3d1493d4c94b.png)
Maybe @amdugas can put up a screen shot of her change as well and then we can decide which pull request to do.

**Comment by amdugas** [comment]
I think Richard's looks better, I just copied the old format from before the server change
![screen shot 2018-10-05 at 2 14 20 pm](https://user-images.githubusercontent.com/40802890/46560586-27596b80-c8a9-11e8-838b-5e9906b12f65.png)
