### ISSUE TITLE
Changes to classification table

### ISSUE THREAD

**Issue by scizen9** [scizen9/sedmpy#32]
Should have the following columns:

id, int  - done
object_id, int  - done
spec_id, ind  - done
classification, text -done
redshift, float  - done
redshift_err, float  - done
phase, float  - done
phase_err, float  - done
classifier, text  - done  (name of classification program: SNID, SuperFit)
score, float  - done

score_type, text  (rlap, chisq, etc.)
auto, bool
source, text   (name of user or robot, could also be 'marshal')
template, text  (template used for classification)

**Comment by rswalters** [comment]
Columns added.  
Note: source and template are reserved SQL words.  I changed the values to class_source and class_template.

**Comment by scizen9** [comment]
Changes accepted, verified, closed.
