### ISSUE TITLE
Rename flexure table to cube and link between observation and spec

### ISSUE THREAD

**Issue by scizen9** [scizen9/sedmpy#33]
This will be the table that will track the generation of the e3d_*.fits cube that is subsequently used for source extraction.  It should be linked to each on-sky observations (standards + science), but not linked to cal observations.  It will incorporate the flexure values currently in the flexure table.

It should have the following columns:

id, int  - done

observation_id, int
ccd_x_flex_corr, bool
ccd_x_flex_px, float
ccd_y_flex_corr, bool
ccd_y_flex_px, float
atm_corr, bool
atm_source, text
atm_mean_corr, float

There may be other columns we add later.

**Comment by scizen9** [comment]
Since flexure will be corrected at the cube stage, we can remove the following items from the spec table:

flexure_x_corr_nm
flexure_y_corr_px
flex_x_px
flex_y_px

**Comment by scizen9** [comment]
We should also add:

spec_calib_id, int
to the cube table and maybe remove it from the spec table.

**Comment by scizen9** [comment]
We will need to add the following to the spec table:

cube_id, int

**Comment by rswalters** [comment]
All changes made to the database and the updated schema is online as well.

**Comment by scizen9** [comment]
verified, closed.
