### ISSUE TITLE
reducer in table spec is wrong type and skysub should be allowed to be null

### ISSUE THREAD

**Issue by scizen9** [scizen9/sedmpy#34]
Column reducer in table spec is now double precision and should be text.
Column skysub has the modifier 'not null' in the spec table and this should be removed.

**Comment by scizen9** [comment]
The columns that should not be allowed to be null (i.e., the required columns) are:

id, spec_calib_id, observation_id, asciifile, and quality.  It looks like you only need to change the skysub and asciifile columns.

**Comment by rswalters** [comment]
Database tables updated with changes

**Comment by scizen9** [comment]
verified changes, closing.
