### ISSUE TITLE
Migrate the photometry pipeline to python3

### ISSUE THREAD

**Issue by amdugas** [scizen9/sedmpy#5]
This was on the Trello, but it very well may have been finished already.

**Comment by scizen9** [comment]
I have made much progress on this, however, work still needs to be done to remove the dependance on pyraf.  If astroconda updates their version of pyraf (which can now handle 64-bit iraf), then we
could still use pyraf.  Another option is to use the package 'ccdproc', which is an associated package of astropy.

**Comment by scizen9** [comment]
removed lots of unused code and cleaned up the rest for python 3.  Working autonomously now.  I consider this issue closed.
