### ISSUE TITLE
Set up backups for the db

### ISSUE THREAD

**Issue by amdugas** [scizen9/sedmpy#8]
Maybe we need to talk to help@astro?

**Comment by nblago** [comment]
I sent an email earlier asking about their current policy and asking to start daily backups for that DB.
Will inform on their response.

**Comment by scizen9** [comment]
Just sent an e-mail to help@astro.caltech.edu.  When I hear back, I'll post the reply here.  Here is my message:

Hi All,

Just checking on the status of the backups for the pharos
postgres database (which appears to be on /var/lib/pgsql).

We are considering some big changes and want to make sure
we are backed up before making them.

Richard told me that you have a new disk for this.  Let me
know if it has been set up and the backups are now running.

Many thanks!
-Don

**Comment by scizen9** [comment]
Here is the reply from Anu.  It looks like they have a nightly backup going, but she
recommends a dump backup every so often by us.  I will mark this closed now.  Here
is here message:

Hello,

Yes, we are backing up /var/lib/pgsql nightly on our backup server.

But, I would strongly recommend that one of you should
set up a cron job to backup the DB using pg_dump command
which will store the backups in user area. Maybe a shell script
to keep a copy per day for a week would be good.

pg_dump -Fc DBNAME -U DBUSER > DUMP_FILE_NAME
